"""espacios_estudio

Revision ID: 00cd0e536834
Revises: c2d3e4f5a6b7
Create Date: 2026-07-29 15:14:51.936099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cd0e536834'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacio_estudio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_evento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_evento_id'], ['tarea_evento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarea_evento_id')
    )
    op.create_table('espacio_estudio_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espacio_estudio_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('seccion', sa.String(length=30), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fecha_referencia', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['espacio_estudio_id'], ['espacio_estudio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espacio_estudio_id', 'documento_id', name='uq_espacio_documento')
    )
    op.create_table('objetivo_espacio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espacio_estudio_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=300), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['espacio_estudio_id'], ['espacio_estudio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objetivo_espacio')
    op.drop_table('espacio_estudio_documento')
    op.drop_table('espacio_estudio')
    # ### end Alembic commands ###
