"""fase 10: nombre_profesor

Revision ID: 41e04bad8c03
Revises: 4328d69e2e5e
Create Date: 2026-07-20 16:10:11.288830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e04bad8c03'
down_revision = '4328d69e2e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_profesor', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignatura', schema=None) as batch_op:
        batch_op.drop_column('nombre_profesor')

    # ### end Alembic commands ###
