"""fase11 metadatos profesor y recurso externo

Revision ID: 4328d69e2e5e
Revises: c73474549a28
Create Date: 2026-07-19 22:32:27.968262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4328d69e2e5e'
down_revision = 'c73474549a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurso_externo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asignatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('despacho_profesor', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('correo_profesor', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('link_aula_virtual', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignatura', schema=None) as batch_op:
        batch_op.drop_column('link_aula_virtual')
        batch_op.drop_column('correo_profesor')
        batch_op.drop_column('despacho_profesor')

    op.drop_table('recurso_externo')
    # ### end Alembic commands ###
