"""tabla dia_actividad para racha de estudio

Revision ID: 5cd17294d4a8
Revises: e1f2a3b4c5d6
Create Date: 2026-09-08 11:42:47.188098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd17294d4a8'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia_actividad',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('fecha')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dia_actividad')
    # ### end Alembic commands ###
