"""indices en columnas muy consultadas

Revision ID: 6db5013308bc
Revises: 00cd0e536834
Create Date: 2026-07-30 13:43:30.199866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db5013308bc'
down_revision = '00cd0e536834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepto_asignatura_id'), ['asignatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepto_proxima_revision'), ['proxima_revision'], unique=False)

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documento_apartado_id'), ['apartado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_asignatura_id'), ['asignatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_fecha_ultima_apertura'), ['fecha_ultima_apertura'], unique=False)
        batch_op.create_index(batch_op.f('ix_documento_grupo_documento_id'), ['grupo_documento_id'], unique=False)

    with op.batch_alter_table('horario_clase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horario_clase_asignatura_id'), ['asignatura_id'], unique=False)

    with op.batch_alter_table('pagina_texto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagina_texto_documento_id'), ['documento_id'], unique=False)

    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profesor_asignatura_id'), ['asignatura_id'], unique=False)

    with op.batch_alter_table('tarea_evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarea_evento_asignatura_id'), ['asignatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarea_evento_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea_evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarea_evento_fecha'))
        batch_op.drop_index(batch_op.f('ix_tarea_evento_asignatura_id'))

    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profesor_asignatura_id'))

    with op.batch_alter_table('pagina_texto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagina_texto_documento_id'))

    with op.batch_alter_table('horario_clase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horario_clase_asignatura_id'))

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_grupo_documento_id'))
        batch_op.drop_index(batch_op.f('ix_documento_fecha_ultima_apertura'))
        batch_op.drop_index(batch_op.f('ix_documento_asignatura_id'))
        batch_op.drop_index(batch_op.f('ix_documento_apartado_id'))

    with op.batch_alter_table('concepto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepto_proxima_revision'))
        batch_op.drop_index(batch_op.f('ix_concepto_asignatura_id'))

    # ### end Alembic commands ###
