"""bloques de evaluacion (nota jerarquica)

Revision ID: 7572e1b913a6
Revises: ee15612bb3a3
Create Date: 2026-09-11 11:22:24.001030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7572e1b913a6'
down_revision = 'ee15612bb3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloque_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('esquema_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['esquema_id'], ['esquema_evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('componente_evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloque_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_componente_evaluacion_bloque_id', 'bloque_evaluacion', ['bloque_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_evaluacion', schema=None) as batch_op:
        batch_op.drop_constraint('fk_componente_evaluacion_bloque_id', type_='foreignkey')
        batch_op.drop_column('bloque_id')

    op.drop_table('bloque_evaluacion')
    # ### end Alembic commands ###
