"""esquemas de evaluacion alternativos

Revision ID: a3ed4ca22390
Revises: 41e04bad8c03
Create Date: 2026-07-20 17:12:59.568594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ed4ca22390'
down_revision = '41e04bad8c03'
branch_labels = None
depends_on = None


def upgrade():
    """
    Reentrante a propósito: en SQLite el DDL hace auto-commit y Alembic no puede
    revertirlo, así que si el proceso muere a media migración (p. ej. el .exe de
    escritorio cerrándose durante el primer arranque) quedan restos a medias y un
    reintento fallaría para siempre con "table ... already exists". Por eso cada
    paso comprueba antes si ya está aplicado, y se limpia la tabla temporal que
    `batch_alter_table` deja atrás cuando se interrumpe.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tablas = set(inspector.get_table_names())

    # Resto de un batch_alter_table interrumpido: sin borrarla, el reintento peta.
    if '_alembic_tmp_componente_evaluacion' in tablas:
        op.drop_table('_alembic_tmp_componente_evaluacion')
        tablas.discard('_alembic_tmp_componente_evaluacion')

    if 'esquema_evaluacion' not in tablas:
        op.create_table('esquema_evaluacion',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('asignatura_id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=200), nullable=False),
        sa.Column('orden', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    columnas_asignatura = {c['name'] for c in inspector.get_columns('asignatura')}
    if 'regla_esquemas' not in columnas_asignatura:
        with op.batch_alter_table('asignatura', schema=None) as batch_op:
            batch_op.add_column(sa.Column('regla_esquemas', sa.String(length=20), nullable=False, server_default='maximo'))

    columnas_componente = {c['name'] for c in inspector.get_columns('componente_evaluacion')}
    if 'esquema_id' not in columnas_componente:
        with op.batch_alter_table('componente_evaluacion', schema=None) as batch_op:
            batch_op.add_column(sa.Column('esquema_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_componente_evaluacion_esquema_id', 'esquema_evaluacion', ['esquema_id'], ['id'])

    _migrar_componentes_a_esquema_unico()


def _migrar_componentes_a_esquema_unico():
    """
    Datos (Fase de esquemas de evaluación): toda asignatura que ya tuviera componentes
    de evaluación sueltos (el único caso posible antes de esta migración) recibe un
    EsquemaEvaluacion "Evaluación" al que se reasignan esos componentes, para que la
    vista de detalle siga funcionando exactamente igual que antes (un único esquema).

    Reentrante como el resto de la migración: solo mira los componentes que todavía
    no tienen esquema asignado, así un reintento tras una interrupción no duplica
    los esquemas ya creados.
    """
    bind = op.get_bind()

    componente_t = sa.table(
        'componente_evaluacion',
        sa.column('id', sa.Integer),
        sa.column('asignatura_id', sa.Integer),
        sa.column('esquema_id', sa.Integer),
    )
    esquema_t = sa.table(
        'esquema_evaluacion',
        sa.column('id', sa.Integer),
        sa.column('asignatura_id', sa.Integer),
        sa.column('nombre', sa.String),
        sa.column('orden', sa.Integer),
    )

    asignatura_ids_con_componentes = bind.execute(
        sa.select(componente_t.c.asignatura_id)
        .where(componente_t.c.esquema_id.is_(None))
        .distinct()
    ).scalars().all()

    for asignatura_id in asignatura_ids_con_componentes:
        bind.execute(
            esquema_t.insert().values(asignatura_id=asignatura_id, nombre='Evaluación', orden=0)
        )
        # El id se relee en vez de usar `inserted_primary_key`: las tablas ligeras de
        # sa.table() no llevan metadatos de clave primaria, así que ese atributo viene
        # vacío y estallaría. Como acabamos de insertar la fila más reciente de esta
        # asignatura, su max(id) es justamente el esquema recién creado.
        nuevo_id = bind.execute(
            sa.select(sa.func.max(esquema_t.c.id))
            .where(esquema_t.c.asignatura_id == asignatura_id)
        ).scalar()
        bind.execute(
            componente_t.update()
            .where(componente_t.c.asignatura_id == asignatura_id)
            .where(componente_t.c.esquema_id.is_(None))
            .values(esquema_id=nuevo_id)
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componente_evaluacion', schema=None) as batch_op:
        batch_op.drop_constraint('fk_componente_evaluacion_esquema_id', type_='foreignkey')
        batch_op.drop_column('esquema_id')

    with op.batch_alter_table('asignatura', schema=None) as batch_op:
        batch_op.drop_column('regla_esquemas')

    op.drop_table('esquema_evaluacion')
    # ### end Alembic commands ###
