"""baseline esquema anterior a fase 11

Revision ID: c73474549a28
Revises: 
Create Date: 2026-07-19 22:31:54.033467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73474549a28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('configuracion_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=10), nullable=False),
    sa.Column('dias_aviso_examen', sa.Integer(), nullable=False),
    sa.Column('dias_asignatura_abandonada', sa.Integer(), nullable=False),
    sa.Column('widgets_orden', sa.String(length=200), nullable=False),
    sa.Column('widgets_ocultos', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuatrimestre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['anio_id'], ['anio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('asignatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuatrimestre_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('creditos_ects', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=True),
    sa.Column('origen_catalogo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('notas_actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuatrimestre_id'], ['cuatrimestre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignatura_prerrequisito',
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('prerrequisito_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['prerrequisito_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('asignatura_id', 'prerrequisito_id')
    )
    op.create_table('componente_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('ultima_revision', sa.Date(), nullable=True),
    sa.Column('proxima_revision', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('prioridad', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('apartado_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_local', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.Column('ultima_pagina_vista', sa.Integer(), nullable=True),
    sa.Column('etiquetas', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['apartado_id'], ['apartado.id'], ),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('numero_pagina', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagina_texto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('numero_pagina', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagina_texto')
    op.drop_table('marcador')
    op.drop_table('documento')
    op.drop_table('tarea_evento')
    op.drop_table('concepto')
    op.drop_table('componente_evaluacion')
    op.drop_table('asignatura_prerrequisito')
    op.drop_table('apartado')
    op.drop_table('asignatura')
    op.drop_table('cuatrimestre')
    op.drop_table('hito')
    op.drop_table('configuracion_app')
    op.drop_table('anio')
    # ### end Alembic commands ###
