"""columna contenido_normalizado precalculada en pagina_texto

Revision ID: c842b67f9507
Revises: 6db5013308bc
Create Date: 2026-07-30 13:49:44.505216

"""
import unicodedata

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c842b67f9507'
down_revision = '6db5013308bc'
branch_labels = None
depends_on = None


def _normalizar(texto):
    """Copia local de utils.normalizar_busqueda: las migraciones no deben depender
    del código de la app, que puede cambiar después de escrita esta migración."""
    if not texto:
        return ""
    descompuesto = unicodedata.normalize("NFKD", texto)
    return "".join(c for c in descompuesto if not unicodedata.combining(c)).lower()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagina_texto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido_normalizado', sa.Text(), nullable=True))

    # ### end Alembic commands ###

    # Backfill: precalcula la versión normalizada del texto ya indexado, para que
    # el buscador global no tenga que volver a normalizarlo en cada petición (spec
    # auditoría: /buscar tardaba ~2s con miles de páginas de PDF indexadas).
    conexion = op.get_bind()
    tabla_pagina_texto = sa.table(
        "pagina_texto",
        sa.column("id", sa.Integer),
        sa.column("contenido", sa.Text),
        sa.column("contenido_normalizado", sa.Text),
    )
    filas = conexion.execute(sa.select(tabla_pagina_texto.c.id, tabla_pagina_texto.c.contenido)).fetchall()
    for fila_id, contenido in filas:
        conexion.execute(
            tabla_pagina_texto.update()
            .where(tabla_pagina_texto.c.id == fila_id)
            .values(contenido_normalizado=_normalizar(contenido))
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagina_texto', schema=None) as batch_op:
        batch_op.drop_column('contenido_normalizado')

    # ### end Alembic commands ###
