"""tabla nota_rapida

Revision ID: cf88a4da32ad
Revises: 5cd17294d4a8
Create Date: 2026-09-08 12:08:03.301968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf88a4da32ad'
down_revision = '5cd17294d4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nota_rapida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=1000), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_rapida')
    # ### end Alembic commands ###
