"""profesor: profesorado multiple por asignatura

Revision ID: d7b267f6cfa5
Revises: f962d2bd0be5
Create Date: 2026-07-28 21:53:10.882507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b267f6cfa5'
down_revision = 'f962d2bd0be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.Column('despacho', sa.String(length=200), nullable=True),
    sa.Column('aula_virtual', sa.String(length=500), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesor')
    # ### end Alembic commands ###
