"""tabla aviso_descartado

Revision ID: ee15612bb3a3
Revises: cf88a4da32ad
Create Date: 2026-09-09 16:11:09.750236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee15612bb3a3'
down_revision = 'cf88a4da32ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso_descartado',
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('tipo', 'entidad_id', 'fecha')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aviso_descartado')
    # ### end Alembic commands ###
