"""documento: nombre_original para auditoria

Revision ID: f962d2bd0be5
Revises: 4543c92b56f8
Create Date: 2026-07-21 12:11:19.346230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f962d2bd0be5'
down_revision = '4543c92b56f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_original', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_column('nombre_original')

    # ### end Alembic commands ###
